### ISSUE TITLE
AttributeError: 'module' object has no attribute 'which'

### ISSUE THREAD

**Issue by fact0real** [DonyorM/weresync#13]
hi all, when I want to install this package I got this error:
```
$ pip install weresync
Collecting weresync
  Downloading WereSync-1.0.7.tar.gz (157kB)
    100% |████████████████████████████████| 163kB 487kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pq/k8mwc5cx6d77wp3nd60m_l8h0000gn/T/pip-build-5M0DNi/weresync/setup.py", line 66, in <module>
        "weresync.resources": ["*.svg", "*.png"] + create_mo_files()
      File "/private/var/folders/pq/k8mwc5cx6d77wp3nd60m_l8h0000gn/T/pip-build-5M0DNi/weresync/setup.py", line 19, in create_mo_files
        if shutil.which("msgfmt") is None:
    AttributeError: 'module' object has no attribute 'which'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/pq/k8mwc5cx6d77wp3nd60m_l8h0000gn/T/pip-build-5M0DNi/weresync/
```
how I can fix it? I'm running macos X.

**Comment by fact0real** [comment]
Oh, we should use python3 to install weresync. I mean:
```
$ pip3 install weresync
Collecting weresync
  Downloading WereSync-1.0.7-py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 175kB/s
Collecting yapsy>=1.11.223 (from weresync)
  Downloading Yapsy-1.11.223.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 292kB/s
Collecting parse>=1.6.6 (from weresync)
  Downloading parse-1.8.2.tar.gz
Building wheels for collected packages: yapsy, parse
  Running setup.py bdist_wheel for yapsy ... done
  Stored in directory: /Users/factoreal/Library/Caches/pip/wheels/fc/ed/0f/3b393c765fd5989bb6c50a3613a4b96037c12c6a40478de796
  Running setup.py bdist_wheel for parse ... done
  Stored in directory: /Users/factoreal/Library/Caches/pip/wheels/b0/3b/37/4ab694a0d331a3cc487923ff9c3645d0f103e9cd4762065f77
Successfully built yapsy parse
Installing collected packages: yapsy, parse, weresync
Successfully installed parse-1.8.2 weresync-1.0.7 yapsy-1.11.223
```

**Comment by DonyorM** [comment]
Just so you know, WereSync isn't made for Mac OS. I highly doubt it will work, the bootloader installation certainly won't. [SuperDuper!](https://www.shirt-pocket.com/SuperDuper/SuperDuperDescription.html) is a better equivalent for Macs.
