### ISSUE TITLE
Python gi module issue

### ISSUE THREAD

**Issue by abal5** [DonyorM/weresync#19]
Python = 3.6
OS = Ubuntu 14 LTS

I seem to be able to install Weresync just fine but get this error message when running the application:

```
Traceback (most recent call last):
  File "/usr/local/bin/weresync", line 11, in <module>
    load_entry_point('WereSync==1.1.5', 'console_scripts', 'weresync')()
  File "/usr/local/lib/python3.6/dist-packages/setuptools-33.1.1-py3.6.egg/pkg_resources/__init__.py", line 561, in load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/setuptools-33.1.1-py3.6.egg/pkg_resources/__init__.py", line 2631, in load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/setuptools-33.1.1-py3.6.egg/pkg_resources/__init__.py", line 2291, in load
  File "/usr/local/lib/python3.6/dist-packages/setuptools-33.1.1-py3.6.egg/pkg_resources/__init__.py", line 2297, in resolve
  File "/usr/local/lib/python3.6/dist-packages/WereSync-1.1.5-py3.6.egg/weresync/interface/cli.py", line 20, in <module>
    import weresync.interface.dbus_client as dbus_client
  File "/usr/local/lib/python3.6/dist-packages/WereSync-1.1.5-py3.6.egg/weresync/interface/dbus_client.py", line 17, in <module>
    from pydbus import SystemBus
  File "/usr/local/lib/python3.6/dist-packages/pydbus-0.6.0-py3.6.egg/pydbus/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pydbus-0.6.0-py3.6.egg/pydbus/bus.py", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 36, in <module>
    from ._gi import _gobject
ModuleNotFoundError: No module named 'gi._gi'
```

I need some help figuring out what is going wrong, I've tried reinstalling python3 many times.

**Comment by refi64** [comment]
Check your installation of pygobject.

-- Ryan
https://refi64.com/

**Comment by kwkimg3100** [comment]
sudo apt install python3-gi

**Comment by DonyorM** [comment]
Did you install with pip or using the .deb file? (Not that you did anything wrong, I just want to make sure my dependencies are set up properly)

Also sorry I took so long to answer, my notifications don't seem to work properly.

**Comment by kidpixo** [comment]
[sorry to reopen this]
I'm installing in virtualen with pipx and weresync doesn't see my system. 
This could be also pipx failure, because it try to separate system from virtualenvs.
When I do my vens I symlink system packages to not replicate everything.

I think pygobject should be explicitly listed in `setup.py` or `requirements.txt` if needed OR separate thing in a way is is called only if one try to open the GUI. 
I have never used it, but I need pygobject anyway...
