### ISSUE TITLE
DBus.Error.AccessDenied

### ISSUE THREAD

**Issue by peterstory** [DonyorM/weresync#20]
I installed weresync on my system using: `pip3 install weresync`

However, when I try to start the weresync-daemon, I get the following error: 
```
peter@peter-DX4831:~$ sudo ~/.local/bin/weresync-daemon
[sudo] password for peter: 
Traceback (most recent call last):
  File "/home/peter/.local/bin/weresync-daemon", line 11, in <module>
    sys.exit(run())
  File "/home/peter/.local/lib/python3.6/site-packages/weresync/daemon/daemon.py", line 37, in run
    with bus.publish("net.manilas.weresync.DriveCopier", DriveCopier()):
  File "/home/peter/.local/lib/python3.6/site-packages/pydbus/publication.py", line 42, in publish
    return Publication(self, bus_name, *objects)
  File "/home/peter/.local/lib/python3.6/site-packages/pydbus/publication.py", line 35, in __init__
    self._at_exit(bus.request_name(bus_name, allow_replacement=allow_replacement, replace=replace).__exit__)
  File "/home/peter/.local/lib/python3.6/site-packages/pydbus/request_name.py", line 29, in request_name
    return NameOwner(self, name, allow_replacement, replace)
  File "/home/peter/.local/lib/python3.6/site-packages/pydbus/request_name.py", line 8, in __init__
    res = bus.dbus.RequestName(name, flags)
  File "/home/peter/.local/lib/python3.6/site-packages/pydbus/proxy_method.py", line 75, in __call__
    0, timeout_to_glib(timeout), None).unpack()
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.114" is not allowed to own the service "net.manilas.weresync.DriveCopier" due to security policies in the configuration file (9)
```

Do you have any suggestions about what I could do to fix this error?

Thanks!
-Peter

**Comment by kwkimg3100** [comment]
same here.

**Comment by DonyorM** [comment]
Sorry this is my bad, I thought I had updated installation documentation.

The [weresync-dbus.conf](https://github.com/DonyorM/weresync/blob/master/src/weresync/resources/weresync-dbus.conf) file needs to be copied to `/etc/dbus-1/system.d/`. That should allow weresync-daemon to run. I'll get more up-to-date installation procedures created later.

However, if you're on a Debian/Ubuntu based distribution, I highly recommend using the .deb package (https://github.com/DonyorM/weresync/releases) to install. It handles all of this for you. Pip can't do that because it would break virtualenv environments I don't want to do that.
