### ISSUE TITLE
PCIe connected NVMe SSDs' partition reading messed up

### ISSUE THREAD

**Issue by Raymo111** [DonyorM/weresync#23]
**EDIT: I didn't mask.
Original issue:**

After I do:
```
sudo weresync-daemon & >/dev/null 2>&1
weresync -vg 2 -E 3 /dev/nvme0n1 /dev/sdb
```
`cat /var/log/weresync/weresync.log` shows:
```
DEBUG - 2019-10-12 19:26:15,964 - weresync.utils - Enabling localization
DEBUG - 2019-10-12 19:26:15,965 - weresync.daemon.copier - making object
DEBUG - 2019-10-12 19:26:15,968 - weresync.daemon.daemon - Starting GLib loop
DEBUG - 2019-10-12 19:26:27,233 - weresync.daemon.copier - Daemon starting clone.
WARNING - 2019-10-12 19:26:28,342 - weresync.daemon.device - Error copying data for partition 1 from device /dev/nvme0n1 to /dev/sdb.
DEBUG - 2019-10-12 19:26:28,342 - weresync.daemon.device - Error info.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 1512, in _copy_files
    source_manager.mount_partition(i, mnt_source)
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/nvme0n1', 'Non-zero exit code. Partition Number: 1', 'mount: /tmp/98224: special device /dev/nvme0n11 does not exist.\n')
WARNING - 2019-10-12 19:26:28,350 - weresync.daemon.device - Error copying data for partition 2 from device /dev/nvme0n1 to /dev/sdb.
DEBUG - 2019-10-12 19:26:28,351 - weresync.daemon.device - Error info.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 1512, in _copy_files
    source_manager.mount_partition(i, mnt_source)
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/nvme0n1', 'Non-zero exit code. Partition Number: 2', 'mount: /tmp/98224: special device /dev/nvme0n12 does not exist.\n')
WARNING - 2019-10-12 19:26:28,356 - weresync.daemon.device - Error copying data for partition 3 from device /dev/nvme0n1 to /dev/sdb.
DEBUG - 2019-10-12 19:26:28,357 - weresync.daemon.device - Error info.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 1512, in _copy_files
    source_manager.mount_partition(i, mnt_source)
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/nvme0n1', 'Non-zero exit code. Partition Number: 3', 'mount: /tmp/98224: special device /dev/nvme0n13 does not exist.\n')
INFO - 2019-10-12 19:26:28,357 - weresync.daemon.device - Using plugin: uuid_copy
DEBUG - 2019-10-12 19:26:28,410 - weresync.daemon.device - Failed to mount partition. Info:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 1346, in _copy_fstab
    source_manager.mount_partition(i, mnt_source)
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/nvme0n1', 'Non-zero exit code. Partition Number: 1', 'mount: /tmp/98224: special device /dev/nvme0n11 does not exist.\n')
DEBUG - 2019-10-12 19:26:28,414 - weresync.daemon.device - Failed to mount partition. Info:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 1346, in _copy_fstab
    source_manager.mount_partition(i, mnt_source)
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/nvme0n1', 'Non-zero exit code. Partition Number: 2', 'mount: /tmp/98224: special device /dev/nvme0n12 does not exist.\n')
DEBUG - 2019-10-12 19:26:28,418 - weresync.daemon.device - Failed to mount partition. Info:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 1346, in _copy_fstab
    source_manager.mount_partition(i, mnt_source)
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/nvme0n1', 'Non-zero exit code. Partition Number: 3', 'mount: /tmp/98224: special device /dev/nvme0n13 does not exist.\n')
WARNING - 2019-10-12 19:26:28,876 - weresync.daemon.device - Error copying bootloader.
DEBUG - 2019-10-12 19:26:28,877 - weresync.daemon.device - Info: 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 1694, in make_bootable
    root_partition, efi_partition)
  File "/usr/lib/python3.7/site-packages/weresync/plugins/weresync_uuid_copy.py", line 54, in install_bootloader
    plugins.translate_uuid(copier, root_partition, "/boot", target_mnt)
  File "/usr/lib/python3.7/site-packages/weresync/plugins/__init__.py", line 56, in translate_uuid
    copier.target.mount_partition(partition, target_mnt)
  File "/usr/lib/python3.7/site-packages/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/sdb', 'Non-zero exit code. Partition Number: 2', 'mount: /tmp/-82531: wrong fs type, bad option, bad superblock on /dev/sdb2, missing codepage or helper program, or other error.\n')
```
The thing is that NVMe drives use `nvme0nXpY` versus the normal `sdXY`, where `X` is the drive number and `Y` is the partition number.

So weresync is looking for a partition at `nvme011` on my laptop, which of course does not exist.

**Comment by Raymo111** [comment]
Masking fixes this issue.

**Comment by DonyorM** [comment]
Is there somewhere in the documentation I could add to make this clearer?

**Comment by kidpixo** [comment]
Hi,
having the same issue.
Maybe a section in the https://weresync.readthedocs.io/ with Masking example would be helpful!

thank you for weresync :+1:
