### ISSUE TITLE
"Error creating logical volume group" during LVM clone

### ISSUE THREAD

**Issue by radusuciu** [DonyorM/weresync#24]
I'm trying to clone a 250GB HDD to a 240GB SSD on Ubuntu Server 18.04. Pretty standard partition layout I think:

```bash
$ lsblk -l
NAME                  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0                   7:0    0    89M  1 loop /snap/core/[redacted]
loop1                   7:1    0  89.1M  1 loop /snap/core/[redacted]
sda                     8:0    0 232.9G  0 disk
sda1                    8:1    0   512M  0 part /boot/efi
sda2                    8:2    0     1G  0 part /boot
sda3                    8:3    0 231.4G  0 part
sdb                     8:16   0 223.6G  0 disk
ubuntu--vg-ubuntu--lv 253:0    0    50G  0 lvm  /
ubuntu--vg-lv--0      253:1    0 181.4G  0 lvm  /home
```

Note that I had some trouble installing with pip, perhaps this is what you mean on the release page. I opted to use the provided `.deb`. Here is what I've issued:

```bash
sudo apt install python3-pydbus
wget https://github.com/DonyorM/weresync/releases/download/v1.1.5/weresync-doc_1.1.5-1_all.deb
sudo dpkg -i weresync-doc_1.1.5-1_all.deb
sudo apt install -f

sudo weresync-daemon > /dev/null 2>&1 &
weresync -C -l ubuntu-vg -B2 -E1 /dev/sda /dev/sdb
```

I get the following error message:

```bash
Partition Table Copying: |████████████████████████████████████████████████████████████| 100.0%
Traceback (most recent call last):
  File "/usr/bin/weresync", line 11, in <module>
    load_entry_point('WereSync==1.1.5', 'console_scripts', 'weresync')()
  File "/usr/share/weresync/weresync/interface/cli.py", line 255, in main
    lvm_target, args.bootloader)
  File "/home/radu/.local/lib/python3.6/site-packages/pydbus/proxy_method.py", line 75, in __call__
    0, timeout_to_glib(timeout), None).unpack()
GLib.Error: g-io-error-quark: GDBus.Error:unknown.DeviceError: ('/dev/sdb', 'Error creating logical volume group.', "  No command with matching syntax recognised.  Run 'vgcreate --help' for more information.\n  Correct command syntax is:\n  vgcreate VG_new PV ...\n\n") (36)
```

and the log:

```bash
DEBUG - 2019-10-28 02:10:48,615 - weresync.daemon.copier - Daemon starting clone.
DEBUG - 2019-10-28 02:10:48,988 - weresync.daemon.device - Partition 3 couldn't be mounted. Bad FS type
Traceback (most recent call last):
  File "/usr/share/weresync/weresync/daemon/device.py", line 1303, in partitions_valid
    i) > target_manager.get_partition_size(i):
  File "/usr/share/weresync/weresync/daemon/device.py", line 332, in get_partition_used
    return int(self._get_general_info(partition_num)[2])
  File "/usr/share/weresync/weresync/daemon/device.py", line 299, in _get_general_info
    self.mount_partition(partition_num, MOUNT_POINT)
  File "/usr/share/weresync/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/sda', 'Non-zero exit code. Partition Number: 3', "mount: /mnt: unknown filesystem type 'LVM2_member'.\n")
INFO - 2019-10-28 02:10:48,989 - weresync.daemon.copier - Drives are compatible
ERROR - 2019-10-28 02:10:49,132 - pydbus.registration - Exception while handling net.manilas.weresync.DriveCopier.CopyDrive()
Traceback (most recent call last):
  File "/home/radu/.local/lib/python3.6/site-packages/pydbus/registration.py", line 81, in call_method
    result = method(*parameters, **kwargs)
  File "/usr/share/weresync/weresync/daemon/copier.py", line 297, in CopyDrive
    target_manager)
  File "/usr/share/weresync/weresync/daemon/copier.py", line 70, in create_new_vg_if_not_exists
    "Error creating logical volume group.")
  File "/usr/share/weresync/weresync/utils.py", line 64, in run_proc
    raise DeviceError(target, error, output)
weresync.exception.DeviceError: ('/dev/sdb', 'Error creating logical volume group.', "  No command with matching syntax recognised.  Run 'vgcreate --help' for more information.\n  Correct command syntax is:\n  vgcreate VG_new PV ...\n\n")
```

Edit: I was specifying the volume group wrong I believe but errors persist:

```bash
$ sudo weresync -v -C -l /dev/ubuntu-vg/ -B2 -E1 /dev/sda /dev/sdb
Partition Table Copying: |████████████████████████████████████████████████████████████| 100.0%
Copying Partition 1.0: |████████████████████████████████████████████████████████████| 100.0%
Copying Partition 2.0: |████████████████████████████████████████████████████████████| 100.0%
Copying Partition 3.0: |------------------------------------------------------------| 0.0%
Some error copying partition 3.0. Probably fine, but see logs.
Bootloader installed
All done, enjoy your drive!
```

and the logs:

```bash

DEBUG - 2019-10-28 04:44:06,767 - weresync.daemon.copier - Daemon starting clone.
DEBUG - 2019-10-28 04:44:07,274 - weresync.daemon.device - Partition 3 couldn't be mounted. Bad FS type
Traceback (most recent call last):
  File "/usr/share/weresync/weresync/daemon/device.py", line 1303, in partitions_valid
    i) > target_manager.get_partition_size(i):
  File "/usr/share/weresync/weresync/daemon/device.py", line 332, in get_partition_used
    return int(self._get_general_info(partition_num)[2])
  File "/usr/share/weresync/weresync/daemon/device.py", line 299, in _get_general_info
    self.mount_partition(partition_num, MOUNT_POINT)
  File "/usr/share/weresync/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/sda', 'Non-zero exit code. Partition Number: 3', "mount: /mnt: unknown filesystem type 'LVM2_member'.\n")
INFO - 2019-10-28 04:44:07,275 - weresync.daemon.copier - Drives are compatible
DEBUG - 2019-10-28 04:44:07,434 - weresync.daemon.copier - PVs in LVM:
INFO - 2019-10-28 04:44:07,457 - weresync.daemon.copier - Drives are compatible
INFO - 2019-10-28 04:44:07,576 - weresync.daemon.device - Starting rsync process for partition /dev/sda.
DEBUG - 2019-10-28 04:44:07,576 - weresync.daemon.device - Arguments = rsync -aAXxH --delete --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* --exclude=/run/* --exclude=/mnt/* --exclude=/media/* --exclude=/lost+found --exclude=/home/*/.gvfs /boot/efi/ /tmp/-33610 --info=progress2
DEBUG - 2019-10-28 04:44:07,596 - weresync.daemon.device - Errors for partition 1:

DEBUG - 2019-10-28 04:44:07,596 - weresync.daemon.device - Setting to finished
INFO - 2019-10-28 04:44:07,646 - weresync.daemon.device - Starting rsync process for partition /dev/sda.
DEBUG - 2019-10-28 04:44:07,646 - weresync.daemon.device - Arguments = rsync -aAXxH --delete --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* --exclude=/run/* --exclude=/mnt/* --exclude=/media/* --exclude=/lost+found --exclude=/home/*/.gvfs /boot/ /tmp/-33610 --info=progress2
DEBUG - 2019-10-28 04:44:07,934 - weresync.daemon.device - Errors for partition 2:

rsync: write failed on "/tmp/-33610/vmlinuz-4.15.0-66-generic": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]

DEBUG - 2019-10-28 04:44:07,934 - weresync.daemon.device - Setting to finished
WARNING - 2019-10-28 04:44:07,993 - weresync.daemon.device - Error copying data for partition 3 from device /dev/sda to /dev/sdb.
DEBUG - 2019-10-28 04:44:07,993 - weresync.daemon.device - Error info.
Traceback (most recent call last):
  File "/usr/share/weresync/weresync/daemon/device.py", line 1512, in _copy_files
    source_manager.mount_partition(i, mnt_source)
  File "/usr/share/weresync/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/sda', 'Non-zero exit code. Partition Number: 3', "mount: /tmp/80420: unknown filesystem type 'LVM2_member'.\n")
INFO - 2019-10-28 04:44:08,006 - weresync.daemon.device - Using plugin: uuid_copy
DEBUG - 2019-10-28 04:44:08,093 - weresync.daemon.device - Failed to mount partition. Info:
Traceback (most recent call last):
  File "/usr/share/weresync/weresync/daemon/device.py", line 1346, in _copy_fstab
    source_manager.mount_partition(i, mnt_source)
  File "/usr/share/weresync/weresync/daemon/device.py", line 175, in mount_partition
    partition_num), str(output, "utf-8"))
weresync.exception.DeviceError: ('/dev/sda', 'Non-zero exit code. Partition Number: 3', "mount: /tmp/80420: unknown filesystem type 'LVM2_member'.\n")
DEBUG - 2019-10-28 04:44:08,232 - parse - format '/dev/{0}' -> '/dev/(.+?)'
DEBUG - 2019-10-28 04:44:08,233 - parse - format '/dev/{0}' -> '/dev/(.+?)'
DEBUG - 2019-10-28 04:44:08,249 - weresync.daemon.device - UUID Dict: {[redacted]}
```

**Comment by DonyorM** [comment]
Sorry that I missed this. The error is odd, but I haven't done a huge amount of testing with LVM so I guess it's not too surprising it didn't work. I'll try to take a look at this over Thanksgiving break.

**Comment by DonyorM** [comment]
Alright @radusuciu I believe the problem is that `-l` expects a volume group name, not a device path.

Try this command instead 
```
sudo weresync  -C -l ubuntu-vg -B 2 -E 1 /dev/sda /dev/sdb
```

Make sure /dev/sda and /dev/sdb are the right drives. `/dev/sdb` is going to be erased, that's bad if it's an important drive.

**Comment by DonyorM** [comment]
Closing since I haven't heard back in a while. Please feel free to reopen if you still have issues.

**Comment by Dylan-86** [comment]
Hi @DonyorM 

I'm back on this since I was trying to do the same today, on a LVM disk


```
sudo weresync  -C -l ubuntu-vg -B 2 -E 1 /dev/nvme0n1 /dev/sdb
Checking partition validity.
WARNING - 2023-11-18 01:59:59,559 - weresync.daemon.copier - Partition count on two drives different. Invalid.
Partitions invalid!
Copying drive partition table.
WARNING - 2023-11-18 01:59:59,559 - weresync.daemon.copier - Drives are incompatible.
The operation has completed successfully.
WARNING - 2023-11-18 02:00:02,933 - weresync.daemon.device - Invalid filesystem type found. Partition 1 not formatted.
WARNING - 2023-11-18 02:00:02,935 - weresync.daemon.device - Invalid filesystem type found. Partition 2 not formatted.
WARNING - 2023-11-18 02:00:02,936 - weresync.daemon.device - Invalid filesystem type found. Partition 3 not formatted.
Partition Table Copying: |████████████████████████████████████████████████████████████| 100.0% 
ERROR - 2023-11-18 02:00:03,129 - pydbus.registration - Exception while handling net.manilas.weresync.DriveCopier.CopyDrive()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pydbus/registration.py", line 81, in call_method
    result = method(*parameters, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/weresync/daemon/copier.py", line 296, in CopyDrive
    create_new_vg_if_not_exists(lvm_source, lvm_source + "-copy",
  File "/usr/local/lib/python3.10/dist-packages/weresync/daemon/copier.py", line 69, in create_new_vg_if_not_exists
    utils.run_proc(["vgcreate", name] + lvm_part_block, target.device,
  File "/usr/local/lib/python3.10/dist-packages/weresync/utils.py", line 64, in run_proc
    raise DeviceError(target, error, output)
weresync.exception.DeviceError: ('/dev/sdb', 'Error creating logical volume group.', "  No command with matching syntax recognised.  Run 'vgcreate --help' for more information.\n  Correct command syntax is:\n  vgcreate VG_new PV ...\n\n")
Traceback (most recent call last):
  File "/usr/local/bin/weresync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/weresync/interface/cli.py", line 250, in main
    result = dbus_client.copy_drive(
  File "/usr/lib/python3/dist-packages/pydbus/proxy_method.py", line 72, in __call__
    ret = instance._bus.con.call_sync(
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:unknown.DeviceError: ('/dev/sdb', 'Error creating logical volume group.', "  No command with matching syntax recognised.  Run 'vgcreate --help' for more information.\n  Correct command syntax is:\n  vgcreate VG_new PV ...\n\n") (36)

```
