### ISSUE TITLE
Fresh out of Synaptic: Linux Mint 20 / Ubuntu

### ISSUE THREAD

**Issue by Axellarator** [DonyorM/weresync#30]
**sudo weresync-gui**

Missing is the weresync-daemon, too

Traceback (most recent call last):
  File "/usr/sbin/weresync-gui", line 11, in <module>
    load_entry_point('WereSync==1.0.7', 'gui_scripts', 'weresync-gui')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/weresync/weresync/gui.py", line 18, in <module>
    import weresync.plugins as plugins
  File "/usr/share/weresync/weresync/plugins/__init__.py", line 29, in <module>
    from distutils.sysconfig import get_python_lib
ModuleNotFoundError: No module named 'distutils.sysconfig'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_weresync_run-gui.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/sbin/weresync-gui", line 11, in <module>
    load_entry_point('WereSync==1.0.7', 'gui_scripts', 'weresync-gui')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/weresync/weresync/gui.py", line 18, in <module>
    import weresync.plugins as plugins
  File "/usr/share/weresync/weresync/plugins/__init__.py", line 29, in <module>
    from distutils.sysconfig import get_python_lib
ModuleNotFoundError: No module named 'distutils.sysconfig'

**Comment by DonyorM** [comment]
that's odd, I'll try and take a look
