### ISSUE TITLE
Failed to connect to dbus service. Is it running?

### ISSUE THREAD

**Issue by Danrancan** [DonyorM/weresync#39]
I installed weresync on Ubuntu 20.04 Server using `pip3 install weresync`.
Then I ran `sudo weresync-daemon & >/dev/null 2>&1` which returns:

`[1] 16114`

running it again returns:

`[2] 16133 Traceback (most recent call last):
  File "/usr/local/bin/weresync-daemon", line 11, in <module>
    load_entry_point('WereSync==1.1.5', 'console_scripts', 'weresync-daemon')()
  File "/usr/local/lib/python3.8/dist-packages/WereSync-1.1.5-py3.8.egg/weresync/daemon/daemon.py", line 37, in run
    with bus.publish("net.manilas.weresync.DriveCopier", DriveCopier()):
  File "/usr/local/lib/python3.8/dist-packages/pydbus-0.6.0-py3.8.egg/pydbus/publication.py", line 42, in publish
    return Publication(self, bus_name, *objects)
  File "/usr/local/lib/python3.8/dist-packages/pydbus-0.6.0-py3.8.egg/pydbus/publication.py", line 35, in __init__
    self._at_exit(bus.request_name(bus_name, allow_replacement=allow_replacement, replace=replace).__exit__)
  File "/usr/local/lib/python3.8/dist-packages/pydbus-0.6.0-py3.8.egg/pydbus/request_name.py", line 29, in request_name
    return NameOwner(self, name, allow_replacement, replace)
  File "/usr/local/lib/python3.8/dist-packages/pydbus-0.6.0-py3.8.egg/pydbus/request_name.py", line 13, in __init__
    raise RuntimeError("name already exists on the bus")
RuntimeError: name already exists on the bus`

I just can't get this to work without being thrown some sort of error no matter what I do. Is this even still under development or some sort of supervision? Please help!

**Comment by DonyorM** [comment]
@Danrancan  Can you post the contents of `/var/log/weresync/weresync.log` and the results of `fdisk -l` (you probably want to make some [gists](http://gist.github.com/) for that.

**Comment by Danrancan** [comment]
I have since deleted my installation. However, I am in the process of spinning up a brand new clean installation. I will do some testing and report back to you. If you don't hear from me within a week, please send me a reminder or tag me in something so I don't forget.

**Comment by Danrancan** [comment]
> I have since deleted my installation. However, I am in the process of spinning up a brand new clean installation. I will do some testing and report back to you. If you don't hear from me within a week, please send me a reminder or tag me in something so I don't forget.

@DonyorM I have since deleted my installation. However, I am in the process of spinning up a brand new clean installation. I will do some testing and report back to you. If you don't hear from me within a week, please send me a reminder or tag me in something so I don't forget. Also, I am very new to github and git. Can you recommend any tutorial for making gists the way you reqested? Not sure how gists differ from just posting the results in here. But I'm down to do things anyway you need me to bud.

**Comment by ThomasHeinrichSchmidt** [comment]
I had to copy `WereSync-1.1.5.tar.gz/dist/WereSync-1.1.5.tar/WereSync-1.1.5/src/weresync/resources/weresync-dbus.conf` from [v1.1.5](https://github.com/DonyorM/weresync/releases/tag/v1.1.5) to `/etc/dbus-1/system.d`. Otherwise I had a permission error `(GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.74" is not allowed to own the service "net.manilas.weresync.DriveCopier" due to security policies in the configuration file (9))`
But still I was  not able to run `sudo weresync-daemon & >/dev/null 2>&1`. 
As soon as I started `$ weresync-gui` I got
```
Job for weresync.service failed because the control process exited with error code.
See "systemctl status weresync.service" and "journalctl -xe" for details.

`$ systemctl status weresync.service`
 ● weresync.service - Weresync Drive Copier
 Loaded: loaded (/lib/systemd/system/weresync.service; static; vendor preset: enabled)
 Active: failed (Result: exit-code) since Mon 2022-03-07 14:46:16 CET; 12min ago
 Process: 5116 ExecStart=/usr/share/weresync/run-daemon (code=exited, status=1/FAILURE)
 Main PID: 5116 (code=exited, status=1/FAILURE) 
```
I could not find out what went wrong and gave up.
