### ISSUE TITLE
Failed to wipe signatures on logical volume

### ISSUE THREAD

**Issue by slyleb** [DonyorM/weresync#40]
Hi !!

I am trying to clone a drive to an smaller SSD with enough free space using the command line since the gui version seem's to work for 2 hours but then errors out saying it cannot start the cloning process.  Now trying to use the command line but I get this error right after the partition table is copied: 

`Partition Table Copying: |████████████████████████████████████████████████████████████| 100.0%
Traceback (most recent call last):
  File "/usr/local/bin/weresync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/weresync/interface/cli.py", line 250, in main
    result = dbus_client.copy_drive(
  File "/usr/lib/python3.10/site-packages/pydbus/proxy_method.py", line 102, in __call__
    raise error
  File "/usr/lib/python3.10/site-packages/pydbus/proxy_method.py", line 97, in __call__
    result = instance._bus.con.call_sync(*call_args)
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:unknown.DeviceError: ('/dev/fedora_localhost-live-copy', 'Error creating new logical volume.', 'WARNING: ext4 signature detected on /dev/fedora_localhost-live-copy/home00 at offset 1080. Wipe it? [y/n]: [n]\n  Aborted wiping of ext4.\n  1 existing signature left on the device.\n  Failed to wipe signatures on logical volume fedora_localhost-live-copy/home00.\n  Aborting. Failed to wipe start of new LV.\n') (36)`

There seem's it got a "wipe it?" command but it automatically awnsers no. 

the command i am using is like this: 
`weresync -C -l fedora_localhost-live -E 1 -B 2 /dev/sdb /dev/sdc`

I'm on Fedora 35, let me know if you need more infos/logs then what's up here. 

Thanks a lot for your help.

sly

**Comment by slyleb** [comment]
Hi again! 

I made some progress in command line mode tonight.  The first 2 partitions (uefi and boot) seemed to be copied fine but when the 3th one starts (LVM2), I get the same error as radusuciu in issue 24. 
https://github.com/DonyorM/weresync/issues/24

`weresync.exception.DeviceError: ('/dev/sdb', 'Non-zero exit code. Partition Number: 3', "mount: /tmp/55411: unknown filesystem type 'LVM2_member'.\n")`

Full log from /var/log/weresync

`[root@z820 weresync]# tail -f weresync.log
WARNING - 2022-01-07 21:28:44,411 - weresync.daemon.device - Error copying data for partition 3 from device /dev/sdb to /dev/sdc.
DEBUG - 2022-01-07 21:28:44,411 - weresync.daemon.device - Error info.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/weresync/daemon/device.py", line 1512, in _copy_files
    source_manager.mount_partition(i, mnt_source)
  File "/usr/local/lib/python3.10/site-packages/weresync/daemon/device.py", line 172, in mount_partition
    raise weresync.exception.DeviceError(
weresync.exception.DeviceError: ('/dev/sdb', 'Non-zero exit code. Partition Number: 3', "mount: /tmp/55411: unknown filesystem type 'LVM2_member'.\n")
INFO - 2022-01-07 21:28:44,584 - weresync.daemon.device - Starting rsync process for partition /dev/fedora_localhost-live.
DEBUG - 2022-01-07 21:28:44,585 - weresync.daemon.device - Arguments = rsync -aAXxH --delete --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/tmp/* --exclude=/run/* --exclude=/mnt/* --exclude=/media/* --exclude=/lost+found --exclude=/home/*/.gvfs /home/ /tmp/-63322 --info=progress2
ERROR - 2022-01-07 22:30:07,773 - pydbus.registration - Exception while handling net.manilas.weresync.DriveCopier.CopyDrive()
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pydbus/registration.py", line 82, in call_method
    result = method(*parameters, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/weresync/daemon/copier.py", line 315, in CopyDrive
    copier.copy_files(
  File "/usr/local/lib/python3.10/site-packages/weresync/daemon/device.py", line 1623, in copy_files
    self._copy_files(mnt_source, mnt_target, excluded_partitions,
  File "/usr/local/lib/python3.10/site-packages/weresync/daemon/device.py", line 1565, in _copy_files
    callback(i, float_val)
  File "/usr/local/lib/python3.10/site-packages/weresync/daemon/copier.py", line 251, in copy_callback
    self.CopyStatus(current, status)
  File "/usr/lib/python3.10/site-packages/pydbus/generic.py", line 52, in __call__
    self.emit(*args)
  File "/usr/lib/python3.10/site-packages/pydbus/generic.py", line 48, in emit
    self.__signal__.emit(self.__self__, *args)
  File "/usr/lib/python3.10/site-packages/pydbus/generic.py", line 91, in emit
    cb(*args)
  File "/usr/lib/python3.10/site-packages/pydbus/registration.py", line 40, in <lambda>
    return lambda *args: self.SignalEmitted(iface.name, signal.name, GLib.Variant("(" + "".join(s.signature for s in signal.args) + ")", args))
  File "/usr/lib/python3.10/site-packages/gi/overrides/GLib.py", line 189, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3.10/site-packages/gi/overrides/GLib.py", line 150, in _create
    builder.add_value(self._create(dup, i))
  File "/usr/lib/python3.10/site-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
TypeError: Must be number, not str
INFO - 2022-01-07 22:30:07,857 - pydbus.registration - name is not registered`

I'm trying to figure out how to put gists in here.  Sorry for that. 

Thanks very much, 

sly

**Comment by DonyorM** [comment]
Would you mind posting the log in a gist (you can do that here: https://gist.github.com/)? It's a little hard to read without linebreaks. it looks like pydbus is having issues, but I would think that would produce a different error message in the console.

**Comment by slyleb** [comment]
ahhh dam Daniel!! 

I was desperate to get up and running for going back to remote work on monday....  that I have chosen to fresh install a new Fedora on the SSD.  I was not sure when you would have time to come back to me so I took the fast lane.  

But just to give you more info if it ever helps... here we're my steps. 

First installed with pip and didnt work out..... but later found a thread on a forum you stating it was a pytihon 3 app and to install with pip3 which is not stated in the docs.   Did not work either for me.   My (new) disk was barebone unalocatted drive.  And was erroring.  The CLI only first worked when I did a bogus virgin partition that engulfed the whole 2 tera drive.  This seemed to erase the signature problem.... And I was able to delete all partitions after to get it back to barebone unallocated.... And the CLI when back to working.  But then gaved this error above your response like issue 24.  

weresync.exception.DeviceError: ('/dev/sdb', 'Non-zero exit code. Partition Number: 3', "mount: /tmp/55411: unknown filesystem type 'LVM2_member'.\n")

Ending up weresync not doing the make bootable part of the process and was ending up giving me 3 seperated drives afterwards.  But it seemed it was really doing the schrink on the partitions, that i can confirm.  

Man you got a crazy project here.  I've searched the internet for almost a week trying to figure out how to do this with clonezilla.  I found a solution in the last couple of days but I was like.... meh...  let's start fresh and put another week going back to the config I had build for years instead.  It's going well and making a good clean up fresh house. 

So, sorry for the noise.  Hoping I have helped you find something out.

Cheers and thanks for getting back to me!   

ps: yeah I saw you told someone else about it. I subscibed to Github only to seek help from you.... so i ma noob.   I am able to do a gist...  But still dont know how to share it here.  


sly

**Comment by DonyorM** [comment]
Yeah it’s been a while since I’ve done much work on this. I didn’t do a lot of testing with LVM so frankly I’m not shocked that I seemed to have missed something. 

Do you know what bootloader/distribution you used? If I have time I might see if I can reproduce the issue

**Comment by slyleb** [comment]
Hi Daniel! 
Its a eufi system using grub2 on fedora 35.  

cheers!
