### ISSUE TITLE
Exception without proper error message

### ISSUE THREAD

**Issue by g3ntleman** [DonyorM/weresync#5]
WereSync Version [0.2]:
Name of Distribution (ex. Ubuntu): lubuntu 16.1
Version of Distribution (ex. 16.04):
Python version (ex. 3.4): 2.7
[Gist](https://gist.github.com) linking to log file (found in /var/log/weresync):
Expected Behavior:

Actual Behavior:

>:~$ weresync -C /dev/sdc /dev/sda
Checking partition validity.
Traceback (most recent call last):
  File "/home/the/.local/bin/weresync", line 11, in <module>
    sys.exit(main())
  File "/home/the/.local/lib/python2.7/site-packages/weresync/interface.py", line 126, in main
    mount_points)
  File "/home/the/.local/lib/python2.7/site-packages/weresync/interface.py", line 62, in copy_drive
    copier.partitions_valid()
  File "/home/the/.local/lib/python2.7/site-packages/weresync/device.py", line 618, in partitions_valid
    source_parts = self.source.get_partitions()
  File "/home/the/.local/lib/python2.7/site-packages/weresync/device.py", line 67, in get_partitions
    raise weresync.exception.DeviceError(self.device, "Non-zero exit code", str(error, "utf-8"))
TypeError: str() takes at most 1 argument (2 given)

Other relevant details:

**Comment by DonyorM** [comment]
WereSync requires python3, not python2. Install it with `pip3 weresync` (you might need to install pip3 with `apt-get install python3-pip`) and it should work fine. I'll try to get a warning message up for when you run under python2. Also be sure to run weresync as root (`sudo weresync`) or else it can't access the block devices for copying.

**Comment by DonyorM** [comment]
Fixed with 891ea97
